dbt_banxware_assignment:
  outputs:
    dev:
      type: SNOWFLAKE
      threads: 4
      account: <your_snowflake_account_details>
      database: <snowflake_database_name>
      user: <login-name>
      password: <yourpassword>
      schema: <your_snowflake_schema_name>
      warehouse: <compute_wh>
      role: <snowflake_role>
  target: dev
